spring:
  application:
    name: tracking_order
  datasource:
    url: jdbc:mysql://localhost:3306/tracking_order_db
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
